resources:
- name: concourse-slack-resource
  type: git
  source:
    uri: https://github.com/zarplata/concourse-slack-resource.git 
    branch: master
    paths:
    - assets
    - Dockerfile

- name: docker-hub
  type: docker-image
  source:
    repository: zarplata/concourse-slack-resource
    username: ((docker-hub.username))
    password: ((docker-hub.password))
    tag: latest

jobs:
- name: release-docker-image
  public: true
  serial: true
  plan:
  - get: concourse-slack-resource
    trigger: true
  - put: docker-hub
    params: {build: concourse-slack-resource}

